language: c
sudo: false
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.2
      addons:
        apt:
          sources:
            - hvr-ghc
          packages:
            - libxxf86vm-dev
            - libglfw-dev
            - cabal-install-1.22
            - ghc-7.10.2

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - cabal install --only-dependencies --enable-tests --enable-library-profiling

script:
  - cabal configure --enable-tests --enable-executable-profiling -v2
  - cabal build
  - cabal test
