sudo: false

language: c

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp
      - libgmp-dev

before_install:
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc test --bench --only-dependencies

script:
  - stack --no-terminal build
